[package]
name = "lex-session"
version = "0.1.0"
edition = "2021"

[lib]
name = "lex_session"

[features]
default = []
trace = ["tracing/max_level_debug", "lex-core/trace"]

[dependencies]
lex-core = { path = "../lex-core" }
tracing = { workspace = true }

[dev-dependencies]
proptest = "1"
